
# Initialize the location of the database
database_path = 'users.sqlite'

# STATES
LANGUAGE, IDENTITY, REGION, CHOOSE_REGION_STATE, REASON, REASON_EDIT_STATE,\
    REO_STATE, FREQUENCY, FREQ_OTHER_STATE, SERVICE_STATE, SERVICE_EDIT_STATE,\
    RATING_SERVICES_CREDIT,\
    RATING_SERVICES_DEPOSIT,\
    RATING_SERVICES_CARD,\
    RATING_SERVICES_PAYMENT,\
    RATING_SERVICES_EXCHANGE,\
    RATING_SERVICES_TRANSFER, \
    RATING_SERVICES_WITHDRAWAL,\
    RATING_PARAMETERS_DEADLINE,\
    RATING_PARAMETERS_FEEDBACK,\
    RATING_PARAMETERS_INFO_AVAILABLE,\
    RATING_PARAMETERS_PERSONAL,\
    RATE_WORKERS_INFORMED, \
    RATE_WORKERS_OPERATIVE,\
    RATE_WORKERS_PROFESSIONAL,\
    RATE_WORKERS_POLITE,\
    RATE_WORKERS_READY_HELP,\
    CHOOSE_STATEMENT_NAVIGATION, \
    CHOOSE_STATEMENT_RESPONSIBILITY, \
    CHOOSE_STATEMENT_BANK_RESPONSE, \
    CHOOSE_STATEMENT_WORKER_INFO, \
    CHOOSE_STATEMENT_BANK_FAILS, \
    CHOOSE_STATEMENT_WORKER_OPERATIVE, \
    CHOOSE_STATEMENT_BANK_ADVANTAGE, \
    CHOOSE_STATEMENT_COMISSION, \
    CHOOSE_STATEMENT_WIDE_RANGE, \
    CHOOSE_STATEMENT_CREDIT_GET, \
    CHOOSE_STATEMENT_APPEREANCE, \
    CHOOSE_STATEMENT_GOOD_PR, \
    CHOOSE_STATEMENT_MOBILE_APP, \
    CHOOSE_STATEMENT_ATM, \
    LIKE_OR_NOT, \
    LON_STATE, COMMENTS = map(chr, range(44))


